version: '3.3'

services:
  php-fpm:
    build: ./
    ports:
      - 5000:8000
    volumes:
      - ./:/var/www/html
    environment:
      APP: myApp
  mysql:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
